name: CI Pipeline

on: [push, pull_request]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
      - name: Install helm
        uses: azure/setup-helm@v3
      - name: Setup flytectl
        uses: unionai-oss/flytectl-setup-action@master
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
